import {
  cilApplicationsSettings,
  cilArrowRight,
  cilColumns,
  cilFolder,
  cilGroup,
  cilHome,
  cilLayers,
  cilLockLocked,
  cilMenu,
  cilMoney,
  cilNotes,
  cilPen,
  cilSettings,
  cilSpeedometer,
  cilTask,
  cilTransfer,
  cilUser,
  cilUserPlus,
  cilWallpaper,
  cilXCircle,
  cilAppsSettings
} from '@coreui/icons';

export const iconSubset = {
  cilTransfer ,
  cilUser ,
  cilColumns ,
  cilFolder ,
  cilTask ,
  cilSettings ,
  cilLockLocked,
  cilArrowRight,
  cilApplicationsSettings,
  cilHome,
  cilMenu,
  cilGroup,
  cilNotes,
  cilUserPlus,
  cilSpeedometer,
  cilMoney,
  cilLayers,
  cilPen,
  cilXCircle,
  cilWallpaper,
};

export enum IconSubset {
  cilApplicationsSettings = 'cilApplicationsSettings',
  cilMenu = 'cilMenu',
  cilSpeedometer = 'cilSpeedometer',
}
