import {
  cilApplicationsSettings,
  cilMenu,
  cilSpeedometer,
  cilPen,
  cilFolder,
  cilTask,
  cilUser,
  cilStorage,
  cilLayers,
  cilShortText,
  cilColumns,cilDescription,
  cilMoney,cilTags,
  cilGroup,cilVerticalAlignBottom,
  cilPaperclip,cilThumbUp,
  cilWallpaper, cilLibraryAdd, cilNotes,
  cilDrop, cilPlus, cilLibrary, cilArrowRight,
  cilTransfer,
  cilUserPlus,
  cilXCircle,
  cilLockLocked,
  cilHome,
  cilSettings,
} from '@coreui/icons';

// export const iconSubset = {
//   cilApplicationsSettings,cilWallpaper,cilPlus,cilThumbUp,
//   cilMenu,cilTask,cilPaperclip,cilNotes,cilLibrary,cilTags,
//   cilSpeedometer,cilStorage,cilLibraryAdd,cilArrowRight,cilDescription,
//   cilFolder,cilUser,cilLayers,cilGroup,cilDrop,cilVerticalAlignBottom,
//   cilPen,cilColumns,cilMoney,cilShortText,
// };

export const iconSubset = {
  cilLibrary,
  cilPlus,
  cilDrop,
  cilLibraryAdd,
  cilThumbUp,
  cilPaperclip,
  cilVerticalAlignBottom,
  cilTags,
  cilDescription,
  cilApplicationsSettings,
  cilMenu,
  cilTask,
  cilArrowRight,
  cilSpeedometer,
  cilStorage,
  cilTransfer,
  cilFolder,
  cilUser,
  cilLayers,
  cilGroup,
  cilPen,
  cilColumns,
  cilMoney,
  cilShortText,
  cilUserPlus,
  cilNotes,
  cilWallpaper,
  cilXCircle,
  cilLockLocked,
  cilHome,
  cilSettings,
};

export enum IconSubset {
  cilApplicationsSettings = 'cilApplicationsSettings',
  cilMenu = 'cilMenu',
  cilSpeedometer = 'cilSpeedometer',
  cilPen='cilPen',
  cilFolder= 'cilFolder',
}
